#ifndef FLIST_ENUMS_H
#define FLIST_ENUMS_H


enum MessageType {
	MESSAGE_TYPE_LOGIN,
	MESSAGE_TYPE_ONLINE,
	MESSAGE_TYPE_OFFLINE,
	MESSAGE_TYPE_STATUS,
	MESSAGE_TYPE_CHANNEL_DESCRIPTION,
	MESSAGE_TYPE_CHANNEL_MODE,
	MESSAGE_TYPE_JOIN,
	MESSAGE_TYPE_LEAVE,
	MESSAGE_TYPE_CHANNEL_INVITE,
	MESSAGE_TYPE_KICK,
	MESSAGE_TYPE_KICKBAN,
	MESSAGE_TYPE_IGNORE_UPDATE,
	MESSAGE_TYPE_SYSTEM,
	MESSAGE_TYPE_REPORT,
	MESSAGE_TYPE_ERROR,
	MESSAGE_TYPE_BROADCAST,
	MESSAGE_TYPE_RPAD,
	MESSAGE_TYPE_CHAT,
	MESSAGE_TYPE_ROLL,
};

enum TypingStatus {
	TYPING_STATUS_CLEAR,
	TYPING_STATUS_TYPING,
	TYPING_STATUS_PAUSED,
};

enum ChannelMode {
	//todo: add an unknown
	CHANNEL_MODE_CHAT,
	CHANNEL_MODE_ADS,
	CHANNEL_MODE_BOTH,
	CHANNEL_MODE_MAX
};

#endif // FLIST_ENUMS_H
